Repository architects-land/difficulty-death-scaler, pull requests merged in 2024-07, with the labels that each got.

#1 Add max player health decrease
  gradle.properties
  src/main/java/world/anhgelus/architectsland/difficultydeathscaler/DifficultyDeathScaler.java
Labels: enhancement

#2 Add a sound effect when the difficulty decreases
  src/main/java/world/anhgelus/architectsland/difficultydeathscaler/DifficultyDeathScaler.java
Labels: enhancement

#3 [Fix] Difficulty on start
  src/main/java/world/anhgelus/architectsland/difficultydeathscaler/DifficultyDeathScaler.java
Labels: enhancement

#5 [Fix] Increasing death number if using a totem of undying
  src/main/java/world/anhgelus/architectsland/difficultydeathscaler/DifficultyDeathScaler.java
Labels: bug

#6 [Feat] Balance the game
  README.md
  src/main/java/world/anhgelus/architectsland/difficultydeathscaler/DifficultyDeathScaler.java
Labels: enhancement

#7 [Feat] command /difficultydeathscaler
  README.md
  gradle.properties
  src/main/java/world/anhgelus/architectsland/difficultydeathscaler/DifficultyDeathScaler.java
Labels: enhancement

#9 [Feat] show time before next decrease on difficulty update
  src/main/java/world/anhgelus/architectsland/difficultydeathscaler/DifficultyDeathScaler.java
Labels: enhancement

#10 [Refactor] Boss reduce difficulty
  gradle.properties
  src/main/java/world/anhgelus/architectsland/difficultydeathscaler/DifficultyDeathScaler.java
  src/main/java/world/anhgelus/architectsland/difficultydeathscaler/DifficultyManager.java
  src/main/java/world/anhgelus/architectsland/difficultydeathscaler/boss/BossManager.java
  src/main/java/world/anhgelus/architectsland/difficultydeathscaler/boss/BuffableBoss.java
Labels: enhancement

#15 [Fix] setNumberDeath does not always update difficulty, and other issue with TimerTask
  gradle.properties
  src/main/java/world/anhgelus/architectsland/difficultydeathscaler/DifficultyManager.java
Labels: bug, enhancement

#16 [Fix] Difficulty changes display
  src/main/java/world/anhgelus/architectsland/difficultydeathscaler/DifficultyDeathScaler.java
  src/main/java/world/anhgelus/architectsland/difficultydeathscaler/DifficultyManager.java
  src/main/java/world/anhgelus/architectsland/difficultydeathscaler/boss/BossManager.java
Labels: bug
