Repository architects-land/difficulty-death-scaler, pull requests merged in 2025-01, with the labels that each got.

#48 [Docs] Fix different mistakes in the wiki
  Writerside/topics/Global-Difficulty.md
Labels: documentation

#50 [Feat] Easier command
  README.md
  Writerside/topics/Command.md
  src/main/java/world/anhgelus/architectsland/difficultydeathscaler/DifficultyDeathScaler.java
  src/main/java/world/anhgelus/architectsland/difficultydeathscaler/difficulty/DifficultyCommand.java
  src/main/java/world/anhgelus/architectsland/difficultydeathscaler/difficulty/DifficultyManager.java
  src/main/java/world/anhgelus/architectsland/difficultydeathscaler/difficulty/global/GlobalDifficultyManager.java
  src/main/java/world/anhgelus/architectsland/difficultydeathscaler/difficulty/player/PlayerDifficultyManager.java
Labels: bug, enhancement

#51 [Fix] Kicking can provoke bugs
  src/main/java/world/anhgelus/architectsland/difficultydeathscaler/DifficultyDeathScaler.java
  src/main/java/world/anhgelus/architectsland/difficultydeathscaler/difficulty/DifficultyCommand.java
  src/main/java/world/anhgelus/architectsland/difficultydeathscaler/difficulty/player/PlayerDifficultyManager.java
  src/main/java/world/anhgelus/architectsland/difficultydeathscaler/mixin/PlayerManagerMixin.java
  src/main/java/world/anhgelus/architectsland/difficultydeathscaler/utils/Getters.java
  src/main/resources/difficultydeathscaler.mixins.json
Labels: bug

#52 [Feat] New spawns
  Writerside/topics/Global-Difficulty.md
  Writerside/topics/Player-Difficulty.md
  Writerside/writerside.cfg
  src/main/java/world/anhgelus/architectsland/difficultydeathscaler/DifficultyDeathScaler.java
  src/main/java/world/anhgelus/architectsland/difficultydeathscaler/boss/Boss.java
  src/main/java/world/anhgelus/architectsland/difficultydeathscaler/boss/BossManager.java
  src/main/java/world/anhgelus/architectsland/difficultydeathscaler/boss/BuffableBoss.java
  src/main/java/world/anhgelus/architectsland/difficultydeathscaler/difficulty/DifficultyCommand.java
  src/main/java/world/anhgelus/architectsland/difficultydeathscaler/difficulty/global/GlobalDifficultyManager.java
  src/main/java/world/anhgelus/architectsland/difficultydeathscaler/difficulty/player/PlayerDifficultyManager.java
  src/main/java/world/anhgelus/architectsland/difficultydeathscaler/mixin/AnnoyingCreeper.java
  src/main/java/world/anhgelus/architectsland/difficultydeathscaler/mixin/AnnoyingDrowned.java
  src/main/java/world/anhgelus/architectsland/difficultydeathscaler/mixin/AnnoyingSkeleton.java
  src/main/java/world/anhgelus/architectsland/difficultydeathscaler/mixin/AnnoyingZombie.java
  src/main/java/world/anhgelus/architectsland/difficultydeathscaler/utils/Getters.java
  src/main/java/world/anhgelus/architectsland/difficultydeathscaler/utils/MobUtils.java
Labels: bug, enhancement
